[package]
name = "remote-colonies"
version = "0.1.0"
authors = ["digitalillusion"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11.3"
gdnative-bindings = "0.11.3"
rand = "0.8.5"
smallvec = "1.10.0"

[profile.release]
opt-level = 1